version: "3"

services:
    mongo:
        image: mongo:7.0.0
        container_name: mongodb_container
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        ports:
            - "27017:27017"
        volumes:
            - ./mongo-data:/data/db

volumes:
    mongo-data:
